productpage:
  namespace: student27-bookinfo-uat
  image: ghcr.io/bordee2000/bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.uat.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student27/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  REVIEWS_HOSTNAME: http://bookinfo-uat-reviews:9080
  RATINGS_HOSTNAME: http://bookinfo-uat-ratings:8080
  DETAILS_HOSTNAME: http://bookinfo-uat-details:8081